# Generated by Django 4.2.4 on 2024-07-25 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_parent_user_remove_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_phone_number',
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.parent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='chemistry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='physics',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
